### ISSUE TITLE
Add launching minimized

### ISSUE THREAD

**Issue by Nerothos** [lucas-bortoli/ntfysh-windows#12]
Hello,

It would be nice if the software would launch without showing the main window and just get into the system tray at startup.

Cheers

**Comment by alexhorner** [comment]
Hi there,

As per the readme, this can already be done with `-t` or `--start-in-tray`. I use this to launch ntfysh-windows at boot from the Task Scheduler.

If you're aware of this function, and are in fact referring to the window appearing briefly before disappearing into the tray at startup, I cannot remember what it was off the top of my head but I did try this and there was a technical limitation.

I'll update this issue to reflect that bug, because that part is indeed valid.

Thanks!

**Comment by Nerothos** [comment]
My bad, I might've overlooked that one. Thanks for the answer
